baseurl = "/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
title = "Tam"
# disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 10
rssLimit = 10
summarylength = 20     # 70 (default)

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disableLanguages = ["de", "nl"]

copyRight = "(c) 2024- Tam"

[build.buildStats]
  enable = true

[outputs]
  home = ["HTML", "RSS", "searchIndex"]
  section = ["HTML", "RSS", "SITEMAP"]

[outputFormats.searchIndex]
  baseName = "search-index"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

# Add output format for section sitemap.xml
[outputFormats.SITEMAP]
  baseName = "sitemap"
  isHTML = false
  isPlainText = true
  mediaType = "application/xml"
  noUgly = true
  rel = "sitemap"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = -1                # "30m"

[taxonomies]
  category = "categories"
  contributor = "contributors"
  tag = "tags"

[permalinks]
  # blog = "/blog/:slug/"
  sciences = "/sciences/:sections[1:]/:slug/"
  docs = "/docs/:sections[1:]/:slug/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "categories"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "date"
    weight = 10

[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 85
  resampleFilter = "Lanczos"
