[en]
  contentDir = "content/en"
  languageName = "English"
  weight = 10
  [en.params]
    # alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
    footer = "copyright © 2024 tambuzztam LLC"
    languageISO = "EN"
    languageTag = "en-US"

# [de]
#   contentDir = "content/de"
#   languageName = "German"
#   weight = 15
#   [de.params]
#     alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'
#     footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
#     languageISO = "DE"
#     languageTag = "de-DE"

# [nl]
#   contentDir = "content/nl"
#   languageName = "Nederlands"
#   weight = 20
#   [nl.params]
#     alertText = 'Introductie van het Doks-kinderthema, verschillende DX + UX-updates en meer! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.2/">Bekijk Doks v0.2</a>'
#     description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
#     footer = 'Mogelijk gemaakt door <a href="https://www.netlify.com/">Netlify</a>, <a href="https://gohugo.io/">Hugo</a>, en <a href="https://getdoks.org/">Doks</a>'
#     languageISO = "NL"
#     languageTag = "nl-NL"
#     titleAddition = "Modern documentatie-thema"
#     titleHome = "Doks thema"
