[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.16.1"
  NPM_VERSION = "9.5.1"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "pnpm build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "pnpm dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
# Redirect all Netlify subdomain traffic to custom domain
[[redirects]]
  from = "https://tam-buzz.netlify.app/*"
  to = "https://tam.buzz/:splat"
  status = 301
  force = true

# Force HTTPS redirect for Netlify subdomain then redirect to custom domain
[[redirects]]
  from = "http://tam-buzz.netlify.app/*"
  to = "https://tam.buzz/:splat"
  status = 301
  force = true

# Force HTTPS for custom domain
[[redirects]]
  from = "http://tam.buzz/*"
  to = "https://tam.buzz/:splat"
  status = 301
  force = true

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
# Following modern CSP best practices with progressive security
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "payment=(), usb=()"
    # CSP for tam.buzz domain
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data: https:; img-src 'self' https://avatars.githubusercontent.com data:; connect-src 'self' https:; manifest-src 'self'; object-src 'none'; base-uri 'self'; frame-src 'self'; frame-ancestors 'none'; form-action 'self';"
    # Allow cross-origin requests (keeping for compatibility)
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Cache-Control = "public, max-age=31536000"
